# 🏍️ MotoGP SQL Practice — Blank Version

In [ ]:
# Setup SQLite database for MotoGP Practice
!pip install ipython-sql sqlalchemy prettytable -q
%load_ext sql
%sql sqlite://
%config SqlMagic.style='PLAIN_COLUMNS'
%config SqlMagic.autopandas=True

%%sql
DROP TABLE IF EXISTS Team; 
DROP TABLE IF EXISTS Rider; 
DROP TABLE IF EXISTS Race; 
DROP TABLE IF EXISTS Result;

CREATE TABLE Team (
  TeamID INTEGER PRIMARY KEY,
  Name TEXT,
  Country TEXT
);

CREATE TABLE Rider (
  RiderID INTEGER PRIMARY KEY,
  Name TEXT,
  Age INTEGER,
  Nationality TEXT,
  TeamID INTEGER,
  FOREIGN KEY(TeamID) REFERENCES Team(TeamID)
);

CREATE TABLE Race (
  RaceID INTEGER PRIMARY KEY,
  Name TEXT,
  Location TEXT,
  Date TEXT
);

CREATE TABLE Result (
  RiderID INTEGER,
  RaceID INTEGER,
  Position INTEGER,
  Points INTEGER,
  PRIMARY KEY (RiderID, RaceID),
  FOREIGN KEY(RiderID) REFERENCES Rider(RiderID),
  FOREIGN KEY(RaceID) REFERENCES Race(RaceID)
);

INSERT INTO Team VALUES
(1,'Ducati Lenovo Team','Italy'),
(2,'Monster Energy Yamaha','Japan'),
(3,'Repsol Honda','Japan'),
(4,'Red Bull KTM','Austria'),
(5,'Aprilia Racing','Italy');

INSERT INTO Rider VALUES
(1,'Francesco Bagnaia',27,'Italy',1),
(2,'Enea Bastianini',26,'Italy',1),
(3,'Fabio Quartararo',25,'France',2),
(4,'Marc Marquez',31,'Spain',3),
(5,'Joan Mir',28,'Spain',3),
(6,'Brad Binder',29,'South Africa',4),
(7,'Jack Miller',30,'Australia',4),
(8,'Maverick Viñales',29,'Spain',5),
(9,'Aleix Espargaro',34,'Spain',5),
(10,'Jorge Martin',26,'Spain',1);

INSERT INTO Race VALUES
(1,'Qatar Grand Prix','Lusail','2024-03-10'),
(2,'Spanish Grand Prix','Jerez','2024-04-28'),
(3,'Italian Grand Prix','Mugello','2024-06-02'),
(4,'Japanese Grand Prix','Motegi','2024-09-29'),
(5,'Malaysian Grand Prix','Sepang','2024-11-03'),
(6,'Valencia Grand Prix','Valencia','2024-11-17');

INSERT INTO Result VALUES
(1,1,1,25),(3,1,2,20),(4,1,3,16),(6,1,4,13),(10,1,5,11),
(1,2,2,20),(10,2,1,25),(4,2,3,16),(6,2,5,11),(8,2,4,13),
(3,3,1,25),(1,3,2,20),(9,3,3,16),(7,3,4,13),(4,3,5,11),
(10,4,1,25),(1,4,2,20),(3,4,3,16),(8,4,4,13),(6,4,5,11),
(1,5,1,25),(2,5,2,20),(3,5,3,16),(6,5,4,13),(4,5,5,11),
(3,6,1,25),(1,6,2,20),(10,6,3,16),(8,6,4,13),(9,6,5,11);

## Section A: Basics

In [ ]:
%%sql
-- Write a query to show Ducati riders

In [ ]:
%%sql
-- Show unique team countries

In [ ]:
%%sql
-- Find races between April and August 2024

In [ ]:
%%sql
-- Riders whose names start with M

## Section B: Joins & Aggregation

In [ ]:
%%sql
-- Rider, team, and total points leaderboard

In [ ]:
%%sql
-- Teams with average points > 15

## Section C: Data Modification

In [ ]:
%%sql
-- INSERT a new rider

In [ ]:
%%sql
-- UPDATE Marc Marquez's team

In [ ]:
%%sql
-- DELETE Malaysian GP

## Section D: Advanced

In [ ]:
%%sql
-- Categorize riders using CASE WHEN

In [ ]:
%%sql
-- Find teams above average total points

In [ ]:
%%sql
-- Simulate penalty with BEGIN/ROLLBACK

## Section E: Challenges

In [ ]:
%%sql
-- Create a leaderboard

In [ ]:
%%sql
-- Find top-scoring team